### PR TITLE
readme: notebook setup instructions for UCL CS

### PR DESCRIPTION
**Pull request by JohannesMaxWel**
Here's instructions to set up the stat-nlp-book on the UCL CS cluster (tested on cannon) and access it through a local browser.

### CODE REVIEW

**Comment by riedelcastro** [comment]
Cool! Does this mean this also works on the machines in the CS lab?

**Comment by riedelcastro** [comment]
Do the MSc students have access to the CS cluster?

**Comment by JohannesMaxWel** [comment]
Good question. As an msc student I did have access to the UCL CS machines (I still use that very account). Not sure how the situation is with students in this year. 

If they do have access they should have received their password on their very first day (i.e. very recently), printed out on a sheet of paper during their induction. Perhaps worth asking them? In case there's students from other departments (business analytics?), they might not have access.

Having all this access should be independent from whether one sits in the CS lab, or at home, or anywhere else. All that's needed is a local browser, and the ssh tunnel.

**Comment by JohannesMaxWel** [comment]
Update from the UCL CS lab:

1) docker cannot be installed without admin rights.
2) going down the virtualenv route works, but one needs to switch to using powershell.exe.
3) Not all of the dependencies could be installed. Concretely, 
`jupyter-nbextension install rise --py --sys-prefix` and
`jupyter-nbextension enable rise --py --sys-prefix`    
cannot be run because 'jupyter-nbextension' is not found. I cannot find this file among the python site-packages. Does it have a different names on windows?

Installing the requirements.txt then fails at the scipy installation due to missing lapack/blas packages.

:/

**Comment by JohannesMaxWel** [comment]
Oh, and every student would have access to these machines using their CS account.

**Comment by riedelcastro** [comment]
Thanks, Jojo!

Don't the clusters have a linux mode as well? Was this in Windows? I'd ask them to work in Linux if that's an option on the cluster.

**Comment by mbosnjak** [comment]
My comment above about making it work refers to Linux.

**Comment by mbosnjak** [comment]
virtualenv installation worked (partially) on Linux when I tried it last year. We just need to verify it still works today.

**Comment by JohannesMaxWel** [comment]
Yes, this was using windows. 

I'm not sure whether one can switch to using linux, but I only worked with the machines in the 'Reuters' room. I didn't see any option for this there.

If they could work with linux that would simplify things quite a bit.

**Comment by mbosnjak** [comment]
You should be able to choose the OS on boot.

**Pull request merged**
